PANDARIA: Delete create ack params zone_id
cnrancher/ack-operator pull request #16
Opened 2023-08-11 03:04 UTC by smallteeths

https://github.com/cnrancher/pandaria/issues/3051

2023-08-16 09:30 UTC, Jason-ZW requested changes

2023-08-16 09:30 UTC, Jason-ZW commented on bin/ack-operator
Useless binary?

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +	if err != nil || clusters == nil {
这里至少需要打印 Debug 级别日志记录 `clusters == nil` 得情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +		return *value
这里 ACK 的 SDK 里没有官方对应的转换方法么？

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
>  		return configSpec, err
至少需要打印 Debug 级别日志记录 `cluster == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +	if err != nil || cluster == nil {
至少需要打印 Debug 级别日志记录 `cluster == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +		return configSpec, nil
至少需要打印 Debug 级别日志记录` configSpec == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +			return configSpec, nil
至少需要打印 Debug 级别日志记录` status == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
>  		return config, err
至少需要打印 Debug 级别日志记录` clusterMap == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +		return config, nil
至少需要打印 Debug 级别日志记录` fixedSpec == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +	if cluster.ClusterId != nil {
是否存在` *cluster.ClusterId == ""` 情况？

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +			return config, nil
至少需要打印 Debug 级别日志记录` status == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
>  		return config, err
至少需要打印 Debug 级别日志记录` cluster == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +			return config, nil
至少需要打印 Debug 级别日志记录` status == nil` 情况

2023-08-16 09:30 UTC, Jason-ZW commented on controller/ack-cluster-config-handler.go
> +		return config, nil
至少需要打印 Debug 级别日志记录` fixedSpec == nil` 情况

2023-08-17 01:31 UTC, smallteeths commented on bin/ack-operator
这个传与不传并不影响实际生成的镜像，如果穿上来就是会省去执行 make 的步骤。我一会更新去掉它

2023-08-17 01:33 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +		return *value
没有官方的转换，这个就是简单的判断下是否是 nil 。

2023-08-17 05:03 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
>  		return config, err
done

2023-08-17 05:03 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +		return config, nil
done

2023-08-17 05:03 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +			return config, nil
done

2023-08-17 05:04 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
>  		return config, err
done

2023-08-17 05:04 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +			return config, nil
done

2023-08-17 05:06 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +		return config, nil
done

2023-08-17 05:06 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +		return configSpec, nil
done

2023-08-17 05:07 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
>  		return configSpec, err
done

2023-08-17 05:07 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +			return configSpec, nil
done

2023-08-17 05:14 UTC, smallteeths commented on bin/ack-operator
done

2023-08-17 05:14 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +	if err != nil || clusters == nil {
done

2023-08-17 05:14 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +	if err != nil || cluster == nil {
done

2023-08-17 05:17 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +	if cluster.ClusterId != nil {
添加 *cluster.ClusterId == "" 这个判断能更准确些 done

2023-08-17 06:54 UTC, GGGitBoy commented
LGTM

2023-08-17 06:57 UTC, STARRY-S requested changes
Little suggestions, others LGTM.

2023-08-17 06:57 UTC, STARRY-S commented on controller/ack-cluster-config-handler.go
>  		return config, err
一点建议哈：
这里的 `err` 为 `nil`，当 `clusterMap == nil` 时，直接返回 `config, nil`，不重新将 `config` Enqueue 的话会使 `status.phase` 一直卡在 `importing`，且 `status.failureMessage` 没有记录到错误信息，Rancher UI 界面上将不会显示报错。

要不把 `return` 这一行改成：
```go
return config, fmt.Errorf("failed to get import cluster: 一些错误信息......")
```
将返回的 `err` 加上错误信息，这样可以将错误记录在 `status.failureMessage` 中，且因为返回的 `err` 不为空，Operator 会尝试重新将 `config` 入队列，反复执行 `importCluster` 函数。  

----

下方其余的几处返回 `config, nil` 同理，建议将其改成 `return config, fmt.Errorf("...")`。

2023-08-17 06:57 UTC, STARRY-S commented on controller/ack-cluster-config-handler.go
> +		Name:                getValueOrDefault(cluster.Name, ""),
这里的 Default Value 都是空字符串，要不使用 `tea.StringValue` 方法？  
`tea` 包是：`"github.com/alibabacloud-go/tea/tea"`

2023-08-17 06:57 UTC, STARRY-S commented on .gitignore
> +bin/
这里加上 `bin/` 但因为 `bin/ack-operator` 二进制文件已经存在且被 Git 跟踪了因此这行 ignore 并没有生效。
建议执行 `git rm -r bin/` 把项目中的二进制文件删掉，防止再次提交上编译后的二进制文件哈。

2023-08-17 09:26 UTC, smallteeths commented on .gitignore
> +bin/
done 已经删除相关的 bin 目录

2023-08-17 09:26 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +		Name:                getValueOrDefault(cluster.Name, ""),
done 谢谢 已经更换官方的转换方式

2023-08-17 09:31 UTC, smallteeths commented on controller/ack-cluster-config-handler.go
> +		Name:                getValueOrDefault(cluster.Name, ""),
我也修改了需要反馈给用户的错误信息，原来我纠结如果 cluster 为 nil 的情况是否需要重新 Enqueue 。确实如果出现这种情况应该告知用户现在是哪里出错了

2023-08-17 09:35 UTC, STARRY-S approved these changes
LGTM, thanks.

2023-08-18 03:09 UTC, Jason-ZW approved these changes

2023-08-18 03:09 UTC, merged